### ISSUE TITLE
error caused by updated FrEIA

### ISSUE THREAD

**Issue by WeianMao** [VLL-HD/conditional_invertible_neural_networks#16]
Traceback (most recent call last):
  File "/media/data/weian/project/imagenet/conditional_INNs/mnist_cINN/train.py", line 28, in <module>
    import model
  File "/media/data/weian/project/imagenet/conditional_INNs/mnist_cINN/model.py", line 42, in <module>
    nodes.append(Node([nodes[-1].out0], flattening_layer, {}, name='flatten'))
NameError: name 'flattening_layer' is not defined

**Comment by Brittany-Chen** [comment]
Hi, I meet the same problem, have you solved it?

**Comment by yuffon** [comment]
@WeianMao @Brittany-Chen Have you solved this problem?
